version: "3.8"

services:
  app:
    build: .
    volumes:
      - ./symfonyapp:/var/www/html
    ports:
      - "8080:80"
    environment:
      - APP_ENV=dev
      - INSTALL_SYMFONY=${INSTALL_SYMFONY:-true}
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_HOST: '%'
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u${DB_USER}", "-p${DB_PASSWORD}"]
      interval: 5s
      timeout: 10s
      retries: 5

volumes:
  db_data: